name: accountech
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.1
  font_awesome_flutter: ^10.1.0
  group_button: ^5.0.1
  dropdown_search: ^5.0.2
  expandable: ^5.0.1
  shared_value: ^3.0.0
  flutter_phoenix: ^1.0.0
  restart_app: ^1.1.0+1
  syncfusion_flutter_datepicker: ^20.1.56
  intl: ^0.17.0
  flutter_switch: ^0.3.2
  flutter_slidable: ^2.0.0
  lottie: ^1.3.0
  modal_bottom_sheet: ^3.0.0-pre
  percent_indicator: ^4.2.2
  dotted_border: ^2.0.0+2
  countdown_progress_indicator: ^0.1.2
  pin_code_fields: ^7.4.0
  file_picker: ^5.1.0
  image_cropper: ^3.0.0
  http: ^0.13.4
  shimmer: ^2.0.0
  basic_utils: ^5.2.2






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie_animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MontserratAlternatesBlack
      fonts:
        - asset: assets/fonts/MontserratAlternates-Black.ttf
          style: normal
    - family: MontserratAlternatesBold
      fonts:
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          style: normal
    - family: MontserratAlternatesExtraBold
      fonts:
        - asset: assets/fonts/MontserratAlternates-ExtraBold.ttf
          style: normal
    - family: MontserratAlternatesExtraLight
      fonts:
        - asset: assets/fonts/MontserratAlternates-ExtraLight.ttf
          style: normal
    - family: MontserratAlternatesLight
      fonts:
        - asset: assets/fonts/MontserratAlternates-Light.ttf
          style: normal
    - family: MontserratAlternatesMedium
      fonts:
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          style: normal
    - family: MontserratAlternatesRegular
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
          style: normal
    - family: MontserratAlternatesSemiBold
      fonts:
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
          style: normal
    - family: MontserratAlternatesThin
      fonts:
        - asset: assets/fonts/MontserratAlternates-Thin.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
